name: RSS to Telegram Workflow

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:
  push:

jobs:
  send_rss_to_telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install the necessary Python packages

      - name: Check if cache directory exists
        run: |
          if [ ! -d ./cache ]; then
            mkdir -p ./cache
            echo "Cache directory created."
          fi

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN_AMZBR: ${{ secrets.TELEGRAM_BOT_TOKEN_AMZBR }}
          TELEGRAM_CHAT_IDAMZBR: ${{ secrets.TELEGRAM_CHAT_IDAMZBR }}
          RSS_FEED_URLAMZBR: ${{ secrets.RSS_FEED_URLAMZBR }}
        run: |
          python send_rss_to_telegram_AMZBR.py
